#! /bin/sh

FILE="main"

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  printf "$ build
Build the project.
"; exit
fi

command -v pdflatex >/dev/null || { echo "pdflatex is not installed"; exit 1; }
command -v biber >/dev/null || { echo "biber is not installed"; exit 1; }

RM_AUX=0

pdflatex main || RM_AUX=1
biber main || RM_AUX=1
pdflatex main || RM_AUX=1

if [ "$RM_AUX" -gt 0 ]; then
  rm main.aux # if things are borked
fi
